spring:
  application:
    name: my-application
  datasource:
    url: jdbc:mysql://localhost:3306/pessoa?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: true
    open-in-view: false